steps:
# Step 1: Run database migrations
- name: 'node:22'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    cd app
    npm ci
    wget https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.8.2/cloud-sql-proxy.linux.amd64 -O /usr/local/bin/cloud-sql-proxy
    chmod +x /usr/local/bin/cloud-sql-proxy
    cloud-sql-proxy --address 0.0.0.0 --port 5432 "${_INSTANCE_CONNECTION_NAME}" &
    sleep 5
    export DATABASE_URL="postgresql://${_DB_USER}:${DB_PASSWORD}@127.0.0.1:5432/${_DB_NAME}"
    npm run db:migrate

# Step 2: Build and push the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/lazy-bear-repo/lazy-bear-app:latest'
  - '-f'
  - 'docker/nextjs/Dockerfile.prod'
  - '.'

images:
- 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/lazy-bear-repo/lazy-bear-app:latest'

substitutions:
  _INSTANCE_CONNECTION_NAME: 'lazy-bear-471016:asia-northeast1:lazy-bear-db-instance'
  _DB_USER: 'lazybear_user'
  _DB_NAME: 'lazy_bear'

secrets:
- secretManager: 
  - versionName: projects/${PROJECT_ID}/secrets/db_password/versions/latest
    env: 'DB_PASSWORD'