version: "3.8"

services:
  # PostgreSQLデータベース
  database:
    build:
      context: .
      dockerfile: docker/postgresql/Dockerfile
    container_name: lazy_bear_database
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Next.jsアプリケーション
  app:
    build:
      context: .
      dockerfile: docker/nextjs/Dockerfile
    container_name: lazy_bear_app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud:ro
    depends_on:
      - database

volumes:
  postgres_data:
