services:
  # PostgreSQLデータベース
  database:
    build:
      context: .
      dockerfile: docker/postgresql/Dockerfile
    container_name: lazy_bear_database
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Next.jsアプリケーション
  app:
    build:
      context: .
      dockerfile: docker/nextjs/Dockerfile
    container_name: lazy_bear_app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - GOOGLE_CLOUD_LOCATION=${GOOGLE_CLOUD_LOCATION}
      - VERTEX_AI_MODEL_NAME=${VERTEX_AI_MODEL_NAME}
    volumes:
      - ./app:/app
      - /app/node_modules
      - ~/.config/gcloud:/root/.config/gcloud:ro
    depends_on:
      - database

volumes:
  postgres_data:
