import { Metadata } from "next";
import { M_PLUS_1p } from "next/font/google";
import "./global.css";

const mplus = M_PLUS_1p({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja" className={mplus.className}>
      <body>{children}</body>
    </html>
  );
}